function AshbyChart()

% ── Colors ───────────────────────────────────────────────────
BG     = [0.08 0.08 0.10];
PANEL  = [0.13 0.13 0.16];
ACCENT = [0.00 0.74 0.84];
TXT_WHT= [1.00 1.00 1.00];
TXT_DIM= [0.70 0.70 0.75];
TXT_ORG= [1.00 0.60 0.15];
TXT_ACC= [0.00 0.74 0.84];
BTN_GRN= [0.10 0.65 0.25];
BTN_RED= [0.75 0.18 0.18];

% ── Material Data ─────────────────────────────────────────────
mat.Name = {
    'Mild Steel','Stainless Steel 304','Tool Steel', ...
    'Aluminium 6061','Aluminium 7075', ...
    'Titanium Ti-6Al-4V','Copper','Brass', ...
    'Cast Iron','Carbon Fibre (CFRP)', ...
    'Magnesium AZ31','Nickel Alloy 718', ...
    'Polycarbonate','Nylon PA66','ABS Plastic', ...
    'Bronze','Tungsten','Inconel 625', ...
    'Glass Fibre (GFRP)','Beryllium'
};
mat.E =        [200,193,210,68.9,71.7,113.8,110,100,170,70,45,200,2.4,2.7,2.3,110,400,205,25,287];
mat.Yield =    [250,215,1500,276,503,880,70,200,250,600,200,1100,55,85,40,120,1500,490,150,345];
mat.Tensile =  [400,505,1900,310,572,950,220,340,350,700,260,1240,65,85,40,310,1510,930,300,448];
mat.Density =  [7.85,8.0,7.85,2.70,2.81,4.43,8.96,8.5,7.20,1.6,1.77,8.19,1.20,1.14,1.05,8.73,19.3,8.44,2.0,1.85];
mat.Hardness = [120,150,600,95,150,334,35,100,215,80,49,370,10,20,10,80,350,240,45,80];
mat.STW =      mat.Tensile ./ mat.Density;
mat.Family = {
    'Metal','Metal','Metal', ...
    'Light Metal','Light Metal', ...
    'Light Metal','Metal','Metal', ...
    'Metal','Composite', ...
    'Light Metal','Metal', ...
    'Polymer','Polymer','Polymer', ...
    'Metal','Metal','Metal', ...
    'Composite','Light Metal'
};

familyColors = containers.Map(...
    {'Metal','Light Metal','Polymer','Composite'}, ...
    {[0.2 0.6 1.0],[0.2 0.9 0.4],[1.0 0.5 0.1],[0.9 0.2 0.8]});

propNames = {'Density (g/cm3)','Young''s Modulus (GPa)', ...
             'Yield Strength (MPa)','Tensile Strength (MPa)', ...
             'Hardness (HB)','Strength-to-Weight Ratio'};
propData  = {mat.Density,mat.E,mat.Yield,mat.Tensile,mat.Hardness,mat.STW};

% ── Figure ───────────────────────────────────────────────────
fig = figure('Name','Ashby Material Selection Chart', ...
    'Position',[50 40 1200 760], ...
    'Color',BG,'NumberTitle','off', ...
    'MenuBar','none','ToolBar','none','Resize','off');

% ── Header ───────────────────────────────────────────────────
uicontrol(fig,'Style','text', ...
    'String','ASHBY MATERIAL SELECTION CHART', ...
    'Units','pixels','Position',[15 728 900 26], ...
    'FontSize',16,'FontWeight','bold', ...
    'ForegroundColor',ACCENT,'BackgroundColor',BG, ...
    'HorizontalAlignment','left');
uicontrol(fig,'Style','text', ...
    'String','Industry-standard tool for optimal material selection', ...
    'Units','pixels','Position',[15 706 900 20], ...
    'FontSize',10,'ForegroundColor',TXT_DIM,'BackgroundColor',BG, ...
    'HorizontalAlignment','left');

% ── Left Panel background ─────────────────────────────────────
uicontrol(fig,'Style','text','String','', ...
    'Units','pixels','Position',[8 8 260 694], ...
    'BackgroundColor',PANEL);

% ── Controls ─────────────────────────────────────────────────
uicontrol(fig,'Style','text','String','X AXIS PROPERTY', ...
    'Units','pixels','Position',[18 682 240 16], ...
    'FontSize',9,'FontWeight','bold', ...
    'ForegroundColor',TXT_ACC,'BackgroundColor',PANEL, ...
    'HorizontalAlignment','left');
xDrop = uicontrol(fig,'Style','popupmenu','String',propNames, ...
    'Units','pixels','Position',[14 646 244 34], ...
    'FontSize',11,'ForegroundColor',TXT_WHT, ...
    'BackgroundColor',[0.11 0.11 0.14],'Value',1);

uicontrol(fig,'Style','text','String','Y AXIS PROPERTY', ...
    'Units','pixels','Position',[18 622 240 16], ...
    'FontSize',9,'FontWeight','bold', ...
    'ForegroundColor',TXT_ACC,'BackgroundColor',PANEL, ...
    'HorizontalAlignment','left');
yDrop = uicontrol(fig,'Style','popupmenu','String',propNames, ...
    'Units','pixels','Position',[14 586 244 34], ...
    'FontSize',11,'ForegroundColor',TXT_WHT, ...
    'BackgroundColor',[0.11 0.11 0.14],'Value',4);

uicontrol(fig,'Style','text','String','BUBBLE SIZE PROPERTY', ...
    'Units','pixels','Position',[18 562 240 16], ...
    'FontSize',9,'FontWeight','bold', ...
    'ForegroundColor',TXT_ACC,'BackgroundColor',PANEL, ...
    'HorizontalAlignment','left');
bDrop = uicontrol(fig,'Style','popupmenu','String',propNames, ...
    'Units','pixels','Position',[14 526 244 34], ...
    'FontSize',11,'ForegroundColor',TXT_WHT, ...
    'BackgroundColor',[0.11 0.11 0.14],'Value',5);

uicontrol(fig,'Style','text','String','AXIS SCALE', ...
    'Units','pixels','Position',[18 500 240 16], ...
    'FontSize',9,'FontWeight','bold', ...
    'ForegroundColor',TXT_ACC,'BackgroundColor',PANEL, ...
    'HorizontalAlignment','left');
xLogCheck = uicontrol(fig,'Style','checkbox','String','Log scale X axis', ...
    'Units','pixels','Position',[14 474 244 28], ...
    'FontSize',10,'ForegroundColor',TXT_WHT,'BackgroundColor',PANEL,'Value',0);
yLogCheck = uicontrol(fig,'Style','checkbox','String','Log scale Y axis', ...
    'Units','pixels','Position',[14 444 244 28], ...
    'FontSize',10,'ForegroundColor',TXT_WHT,'BackgroundColor',PANEL,'Value',0);

uicontrol(fig,'Style','text','String','FILTER BY FAMILY', ...
    'Units','pixels','Position',[18 414 240 16], ...
    'FontSize',9,'FontWeight','bold', ...
    'ForegroundColor',TXT_ACC,'BackgroundColor',PANEL, ...
    'HorizontalAlignment','left');
showMetal = uicontrol(fig,'Style','checkbox','String','Metals', ...
    'Units','pixels','Position',[14 388 244 26], ...
    'FontSize',10,'ForegroundColor',[0.2 0.6 1.0],'BackgroundColor',PANEL,'Value',1);
showLight = uicontrol(fig,'Style','checkbox','String','Light Metals', ...
    'Units','pixels','Position',[14 360 244 26], ...
    'FontSize',10,'ForegroundColor',[0.2 0.9 0.4],'BackgroundColor',PANEL,'Value',1);
showPoly  = uicontrol(fig,'Style','checkbox','String','Polymers', ...
    'Units','pixels','Position',[14 332 244 26], ...
    'FontSize',10,'ForegroundColor',[1.0 0.5 0.1],'BackgroundColor',PANEL,'Value',1);
showComp  = uicontrol(fig,'Style','checkbox','String','Composites', ...
    'Units','pixels','Position',[14 304 244 26], ...
    'FontSize',10,'ForegroundColor',[0.9 0.2 0.8],'BackgroundColor',PANEL,'Value',1);

showLabels = uicontrol(fig,'Style','checkbox','String','Show material labels', ...
    'Units','pixels','Position',[14 268 244 28], ...
    'FontSize',10,'ForegroundColor',TXT_WHT,'BackgroundColor',PANEL,'Value',1);

uicontrol(fig,'Style','pushbutton','String','PLOT CHART', ...
    'Units','pixels','Position',[14 210 244 46], ...
    'FontSize',13,'FontWeight','bold', ...
    'ForegroundColor',TXT_WHT,'BackgroundColor',BTN_GRN, ...
    'Callback',@(~,~) plotChart());
uicontrol(fig,'Style','pushbutton','String','CLEAR', ...
    'Units','pixels','Position',[14 156 244 44], ...
    'FontSize',12,'ForegroundColor',TXT_WHT,'BackgroundColor',BTN_RED, ...
    'Callback',@(~,~) clearChart());

uicontrol(fig,'Style','text','String','SELECTED MATERIAL INFO', ...
    'Units','pixels','Position',[18 132 240 16], ...
    'FontSize',9,'FontWeight','bold', ...
    'ForegroundColor',TXT_ORG,'BackgroundColor',PANEL, ...
    'HorizontalAlignment','left');
infoBox = uicontrol(fig,'Style','text', ...
    'String','Click any bubble to see material details.', ...
    'Units','pixels','Position',[14 14 244 114], ...
    'FontSize',9,'ForegroundColor',[0.85 0.85 0.85], ...
    'BackgroundColor',[0.10 0.10 0.13], ...
    'HorizontalAlignment','left');

% ── Axes ─────────────────────────────────────────────────────
ax = axes(fig,'Units','pixels','Position',[295 30 890 645]);
ax.Color     = [0.10 0.10 0.13];
ax.XColor    = TXT_DIM;
ax.YColor    = TXT_DIM;
ax.GridColor = [0.22 0.22 0.25];
ax.XGrid     = 'on';
ax.YGrid     = 'on';
ax.Box       = 'off';
ax.FontSize  = 10;
ax.Title.Color   = TXT_WHT;
ax.Title.FontSize = 12;
uistack(ax,'top');

% Store plotted data for click detection
plotted.x   = [];
plotted.y   = [];
plotted.idx = [];

% ── Figure click handler ──────────────────────────────────────
set(fig,'WindowButtonDownFcn',@figClick);

% ════════════════════════════════════════════════════════════
%  NESTED FUNCTIONS
% ════════════════════════════════════════════════════════════

    function plotChart()
        cla(ax);
        axes(ax); %#ok
        hold(ax,'on');

        xIdx  = get(xDrop,'Value');
        yIdx  = get(yDrop,'Value');
        bIdx  = get(bDrop,'Value');
        xData = propData{xIdx};
        yData = propData{yIdx};
        bData = propData{bIdx};

        % Normalize bubble sizes
        bNorm = (bData-min(bData))/(max(bData)-min(bData)+eps);
        bSize = 300 + bNorm*1800;

        % Which families to show
        showFamilies = {};
        if get(showMetal,'Value'); showFamilies{end+1} = 'Metal';       end
        if get(showLight,'Value'); showFamilies{end+1} = 'Light Metal'; end
        if get(showPoly, 'Value'); showFamilies{end+1} = 'Polymer';     end
        if get(showComp, 'Value'); showFamilies{end+1} = 'Composite';   end

        % Reset plotted data
        plotted.x   = [];
        plotted.y   = [];
        plotted.idx = [];

        for i = 1:length(mat.Name)
            fam = mat.Family{i};
            if ~ismember(fam,showFamilies); continue; end
            col = familyColors(fam);
            scatter(ax,xData(i),yData(i),bSize(i),col, ...
                'filled','MarkerEdgeColor','w', ...
                'MarkerFaceAlpha',0.85,'LineWidth',0.8);
            if get(showLabels,'Value')
                text(ax,xData(i),yData(i),['  ' mat.Name{i}], ...
                    'Color',TXT_WHT,'FontSize',8, ...
                    'VerticalAlignment','middle');
            end
            % Store for click detection
            plotted.x(end+1)   = xData(i);
            plotted.y(end+1)   = yData(i);
            plotted.idx(end+1) = i;
        end

        % Log scale
        if get(xLogCheck,'Value'); ax.XScale='log'; else; ax.XScale='linear'; end
        if get(yLogCheck,'Value'); ax.YScale='log'; else; ax.YScale='linear'; end

        % Padding
        xl = xlim(ax); yl = ylim(ax);
        if get(xLogCheck,'Value')
            xlim(ax,[xl(1)*0.7 xl(2)*1.5]);
        else
            pad = (xl(2)-xl(1))*0.1;
            xlim(ax,[xl(1)-pad xl(2)+pad]);
        end
        if get(yLogCheck,'Value')
            ylim(ax,[yl(1)*0.7 yl(2)*1.5]);
        else
            pad = (yl(2)-yl(1))*0.1;
            ylim(ax,[yl(1)-pad yl(2)+pad]);
        end

        % Axis labels
        ax.XLabel.String   = propNames{xIdx};
        ax.XLabel.Color    = TXT_DIM;
        ax.XLabel.FontSize = 11;
        ax.YLabel.String   = propNames{yIdx};
        ax.YLabel.Color    = TXT_DIM;
        ax.YLabel.FontSize = 11;
        ax.Title.String    = sprintf('Ashby Chart  —  %s  vs  %s', ...
            propNames{xIdx},propNames{yIdx});
        ax.Title.Color     = TXT_WHT;

        % Legend
        families = {'Metal','Light Metal','Polymer','Composite'};
        famCols  = {[0.2 0.6 1.0],[0.2 0.9 0.4],[1.0 0.5 0.1],[0.9 0.2 0.8]};
        legH = [];
        for f = 1:4
            if ismember(families{f},showFamilies)
                legH(end+1) = scatter(ax,NaN,NaN,120,famCols{f}, ...
                    'filled','DisplayName',families{f}); %#ok
            end
        end
        if ~isempty(legH)
            legend(ax,legH,'Location','northwest', ...
                'TextColor',TXT_WHT,'Color',[0.12 0.12 0.15], ...
                'EdgeColor',[0.3 0.3 0.3],'FontSize',10);
        end

        hold(ax,'off');
        drawnow;
    end

    function figClick(~,~)
        % Only respond to clicks inside the axes
        cp = get(ax,'CurrentPoint');
        cx = cp(1,1);
        cy = cp(1,2);
        xl = xlim(ax);
        yl = ylim(ax);
        if cx < xl(1) || cx > xl(2) || cy < yl(1) || cy > yl(2)
            return;
        end
        if isempty(plotted.x); return; end

        xIdx  = get(xDrop,'Value');
        yIdx  = get(yDrop,'Value');
        bIdx  = get(bDrop,'Value');

        % Normalize distances so x and y scales don't bias result
        xRange = xl(2)-xl(1); if xRange==0; xRange=1; end
        yRange = yl(2)-yl(1); if yRange==0; yRange=1; end

        if strcmp(ax.XScale,'log')
            dx = (log10(plotted.x+eps) - log10(cx+eps)) / ...
                 (log10(xl(2)+eps) - log10(xl(1)+eps));
        else
            dx = (plotted.x - cx) / xRange;
        end
        if strcmp(ax.YScale,'log')
            dy = (log10(plotted.y+eps) - log10(cy+eps)) / ...
                 (log10(yl(2)+eps) - log10(yl(1)+eps));
        else
            dy = (plotted.y - cy) / yRange;
        end

        dists = sqrt(dx.^2 + dy.^2);
        [~,closest] = min(dists);
        matIdx = plotted.idx(closest);

        % Show info
        xVal = propData{xIdx}(matIdx);
        yVal = propData{yIdx}(matIdx);
        bVal = propData{bIdx}(matIdx);
        txt  = sprintf('%s\nFamily: %s\n\n%s: %.2f\n%s: %.2f\n%s: %.2f', ...
            mat.Name{matIdx}, mat.Family{matIdx}, ...
            propNames{xIdx}, xVal, ...
            propNames{yIdx}, yVal, ...
            propNames{bIdx}, bVal);
        set(infoBox,'String',txt);
    end

    function clearChart()
        cla(ax);
        ax.XScale = 'linear'; ax.YScale = 'linear';
        ax.Title.String  = '';
        ax.XLabel.String = '';
        ax.YLabel.String = '';
        plotted.x = []; plotted.y = []; plotted.idx = [];
        set(infoBox,'String','Click any bubble to see material details.');
        drawnow;
    end

end