function MaterialDashboard()
 
% ── Colors ───────────────────────────────────────────────────
BG      = [0.08 0.08 0.10];
PANEL   = [0.13 0.13 0.16];
ACCENT  = [0.00 0.74 0.84];
BTN_GRN = [0.10 0.65 0.25];
BTN_RED = [0.75 0.18 0.18];
BTN_BLU = [0.15 0.40 0.75];
BTN_PRP = [0.55 0.25 0.75];
TXT_WHT = [1.00 1.00 1.00];
TXT_DIM = [0.70 0.70 0.75];
TXT_ACC = [0.00 0.74 0.84];
TXT_ORG = [1.00 0.60 0.15];
 
% ── Material Data ─────────────────────────────────────────────
mat.Name = {
    'Mild Steel','Stainless Steel 304','Tool Steel', ...
    'Aluminium 6061','Aluminium 7075', ...
    'Titanium Ti-6Al-4V','Copper','Brass', ...
    'Cast Iron','Carbon Fibre (CFRP)', ...
    'Magnesium AZ31','Nickel Alloy 718', ...
    'Polycarbonate','Nylon PA66','ABS Plastic', ...
    'Bronze','Tungsten','Inconel 625', ...
    'Glass Fibre (GFRP)','Beryllium'
};
mat.E =       [200,193,210,68.9,71.7,113.8,110,100,170,70,45,200,2.4,2.7,2.3,110,400,205,25,287];
mat.Yield =   [250,215,1500,276,503,880,70,200,250,600,200,1100,55,85,40,120,1500,490,150,345];
mat.Tensile = [400,505,1900,310,572,950,220,340,350,700,260,1240,65,85,40,310,1510,930,300,448];
mat.Density = [7.85,8.0,7.85,2.70,2.81,4.43,8.96,8.5,7.20,1.6,1.77,8.19,1.20,1.14,1.05,8.73,19.3,8.44,2.0,1.85];
mat.Hardness =[120,150,600,95,150,334,35,100,215,80,49,370,10,20,10,80,350,240,45,80];
mat.Poisson = [0.29,0.27,0.28,0.33,0.33,0.34,0.34,0.34,0.26,0.27,0.35,0.31,0.37,0.39,0.35,0.34,0.28,0.31,0.20,0.08];
mat.STW =     mat.Tensile ./ mat.Density;
 
mat.Info = {
    'Mild Steel: General construction, automotive body panels, pipelines, machinery frames.', ...
    'Stainless Steel 304: Kitchen equipment, chemical tanks, medical instruments, marine fittings.', ...
    'Tool Steel: Cutting tools, dies, moulds, drill bits, high-wear components.', ...
    'Aluminium 6061: Aerospace structures, bicycle frames, marine fittings, automotive parts.', ...
    'Aluminium 7075: Aircraft wings, aerospace frames, high-stress structural parts.', ...
    'Titanium Ti-6Al-4V: Jet engines, biomedical implants, racing components, aerospace frames.', ...
    'Copper: Electrical wiring, heat exchangers, plumbing, electronics.', ...
    'Brass: Valves, fittings, musical instruments, decorative hardware.', ...
    'Cast Iron: Engine blocks, brake discs, machine tool frames, pipes.', ...
    'Carbon Fibre (CFRP): Aerospace structures, sports equipment, racing cars, wind turbine blades.', ...
    'Magnesium AZ31: Aerospace panels, laptop casings, camera bodies, automotive parts.', ...
    'Nickel Alloy 718: Jet engine turbines, rocket motors, nuclear reactors, cryogenic tanks.', ...
    'Polycarbonate: Safety helmets, bulletproof glass, optical lenses, electronic housings.', ...
    'Nylon PA66: Gears, bearings, bushings, automotive under-hood components.', ...
    'ABS Plastic: Consumer electronics, automotive trim, 3D printing, toys.', ...
    'Bronze: Bearings, bushings, marine propellers, sculptures, springs.', ...
    'Tungsten: Radiation shielding, cutting tools, electrical contacts, rocket nozzles.', ...
    'Inconel 625: Gas turbines, chemical processing, offshore oil equipment, exhaust systems.', ...
    'Glass Fibre (GFRP): Boat hulls, wind turbine blades, storage tanks, automotive body panels.', ...
    'Beryllium: Aerospace mirrors, nuclear reactors, X-ray windows, precision instruments.'
};
 
useCases = {'Aerospace','Automotive','Biomedical','Construction','Marine','Electronics'};
recommendations = {
    {'Titanium Ti-6Al-4V','Carbon Fibre (CFRP)','Aluminium 7075'}, ...
    {'Mild Steel','Aluminium 6061','Cast Iron'}, ...
    {'Titanium Ti-6Al-4V','Stainless Steel 304','Polycarbonate'}, ...
    {'Mild Steel','Cast Iron','Glass Fibre (GFRP)'}, ...
    {'Stainless Steel 304','Bronze','Glass Fibre (GFRP)'}, ...
    {'Copper','Beryllium','Polycarbonate'}
};
reasonsMap = {
    'High strength-to-weight ratio, excellent fatigue resistance.|Extremely lightweight with very high tensile strength.|Good strength-to-weight, widely used in aircraft structures.', ...
    'Cost-effective, high availability, good weldability.|Lightweight reduces fuel consumption, good corrosion resistance.|Excellent wear resistance for engine blocks and brake discs.', ...
    'Biocompatible, corrosion resistant, high strength.|Corrosion resistant, easy to sterilize, widely approved.|Transparent, impact resistant, used in medical devices.', ...
    'High tensile strength, low cost, widely available.|High compressive strength, good vibration damping.|Corrosion resistant, lightweight, good for panels.', ...
    'Excellent corrosion resistance in seawater.|Good corrosion resistance, used in marine propellers.|Lightweight, corrosion resistant, used in boat hulls.', ...
    'Best electrical conductor, excellent thermal conductivity.|High stiffness, used in precision electronic components.|Good insulator, impact resistant, transparent options.'
};
 
% ════════════════════════════════════════════════════════════
%  MAIN FIGURE
% ════════════════════════════════════════════════════════════
fig = uifigure('Name','MatProp Dashboard  |  v2.0', ...
    'Position',[40 30 1340 820], ...
    'Color',BG);
 
% ── Header ───────────────────────────────────────────────────
uilabel(fig, ...
    'Text','MATERIAL PROPERTIES COMPARISON DASHBOARD', ...
    'Position',[15 788 900 24], ...
    'FontSize',15,'FontWeight','bold','FontColor',ACCENT);
uilabel(fig, ...
    'Text','v2.0  |  20 Materials  |  7 Properties', ...
    'Position',[1060 790 270 20], ...
    'FontSize',10,'FontColor',TXT_DIM);
 
% ── Divider line ─────────────────────────────────────────────
uipanel(fig,'Position',[8 778 1324 3], ...
    'BackgroundColor',ACCENT,'BorderType','none');
 
% ════════════════════════════════════════════════════════════
%  LEFT PANEL
% ════════════════════════════════════════════════════════════
uipanel(fig,'Position',[8 8 252 765], ...
    'BackgroundColor',PANEL,'BorderType','none');
 
% Materials section
uilabel(fig,'Text','SELECT MATERIALS', ...
    'Position',[18 755 220 16], ...
    'FontSize',9,'FontWeight','bold','FontColor',TXT_ACC);
lst = uilistbox(fig, ...
    'Position',[14 555 240 196], ...
    'Items',mat.Name, ...
    'Multiselect','on', ...
    'BackgroundColor',[0.11 0.11 0.14], ...
    'FontColor',TXT_WHT,'FontSize',11, ...
    'ValueChangedFcn',@(~,~) showInfo());
 
% Property section
uilabel(fig,'Text','PROPERTY TO CHART', ...
    'Position',[18 535 220 16], ...
    'FontSize',9,'FontWeight','bold','FontColor',TXT_ACC);
dd = uidropdown(fig, ...
    'Position',[14 495 240 36], ...
    'Items',{'Young''s Modulus (GPa)','Yield Strength (MPa)', ...
             'Tensile Strength (MPa)','Density (g/cm3)', ...
             'Hardness (HB)','Strength-to-Weight Ratio'}, ...
    'BackgroundColor',[0.11 0.11 0.14], ...
    'FontColor',TXT_WHT,'FontSize',11);
 
% Action buttons
uilabel(fig,'Text','ACTIONS', ...
    'Position',[18 472 220 16], ...
    'FontSize',9,'FontWeight','bold','FontColor',TXT_ACC);
uibutton(fig,'Text','COMPARE', ...
    'Position',[14 428 116 40], ...
    'FontSize',11,'FontWeight','bold', ...
    'BackgroundColor',BTN_GRN,'FontColor',TXT_WHT, ...
    'ButtonPushedFcn',@(~,~) updateDashboard());
uibutton(fig,'Text','CLEAR', ...
    'Position',[138 428 116 40], ...
    'FontSize',11,'FontWeight','bold', ...
    'BackgroundColor',BTN_RED,'FontColor',TXT_WHT, ...
    'ButtonPushedFcn',@(~,~) clearAll());
uibutton(fig,'Text','EXPORT CSV', ...
    'Position',[14 384 240 38], ...
    'FontSize',11, ...
    'BackgroundColor',BTN_BLU,'FontColor',TXT_WHT, ...
    'ButtonPushedFcn',@(~,~) exportCSV());
 
% Recommender section
uilabel(fig,'Text','MATERIAL RECOMMENDER', ...
    'Position',[18 358 220 16], ...
    'FontSize',9,'FontWeight','bold','FontColor',TXT_ORG);
uilabel(fig,'Text','Use Case:', ...
    'Position',[18 336 100 16], ...
    'FontSize',10,'FontColor',TXT_DIM);
ucDrop = uidropdown(fig, ...
    'Position',[14 296 240 36], ...
    'Items',useCases, ...
    'BackgroundColor',[0.11 0.11 0.14], ...
    'FontColor',TXT_WHT,'FontSize',11);
uibutton(fig,'Text','RECOMMEND', ...
    'Position',[14 250 240 40], ...
    'FontSize',11,'FontWeight','bold', ...
    'BackgroundColor',BTN_PRP,'FontColor',TXT_WHT, ...
    'ButtonPushedFcn',@(~,~) showRecommendation());
 
% Status
status = uilabel(fig, ...
    'Text','Ready — select materials and click Compare.', ...
    'Position',[14 210 240 36], ...
    'WordWrap','on', ...
    'FontSize',9,'FontColor',[0.5 0.9 0.4]);
 
% Info section
uilabel(fig,'Text','MATERIAL INFO', ...
    'Position',[18 188 220 16], ...
    'FontSize',9,'FontWeight','bold','FontColor',TXT_ORG);
infoBox = uitextarea(fig, ...
    'Position',[14 12 240 173], ...
    'Editable','off', ...
    'BackgroundColor',[0.11 0.11 0.14], ...
    'FontColor',[0.85 0.85 0.85],'FontSize',10, ...
    'Value',{'Click any material','to view its applications.'});
 
% ════════════════════════════════════════════════════════════
%  RIGHT AREA — TABLE
% ════════════════════════════════════════════════════════════
uilabel(fig,'Text','PROPERTIES TABLE', ...
    'Position',[270 758 400 16], ...
    'FontSize',9,'FontWeight','bold','FontColor',TXT_ACC);
tbl = uitable(fig,'Position',[268 618 1064 136]);
 
% ════════════════════════════════════════════════════════════
%  CHARTS
% ════════════════════════════════════════════════════════════
 
% Bar chart
uilabel(fig,'Text','PROPERTY BAR CHART', ...
    'Position',[270 600 300 16], ...
    'FontSize',9,'FontWeight','bold','FontColor',TXT_ACC);
ax1 = uiaxes(fig,'Position',[268 388 508 208]);
ax1.Color      = [0.10 0.10 0.13];
ax1.XColor     = TXT_DIM;
ax1.YColor     = TXT_DIM;
ax1.Title.Color= TXT_WHT;
ax1.Title.FontSize = 11;
ax1.GridColor  = [0.25 0.25 0.28];
ax1.XGrid      = 'on';
ax1.YGrid      = 'on';
 
% STW chart
uilabel(fig,'Text','STRENGTH-TO-WEIGHT RATIO', ...
    'Position',[786 600 350 16], ...
    'FontSize',9,'FontWeight','bold','FontColor',TXT_ACC);
ax2 = uiaxes(fig,'Position',[784 388 548 208]);
ax2.Color      = [0.10 0.10 0.13];
ax2.XColor     = TXT_DIM;
ax2.YColor     = TXT_DIM;
ax2.Title.Color= TXT_WHT;
ax2.Title.FontSize = 11;
ax2.GridColor  = [0.25 0.25 0.28];
ax2.XGrid      = 'on';
ax2.YGrid      = 'on';
 
% Radar chart
uilabel(fig,'Text','RADAR CHART — NORMALIZED PROPERTIES', ...
    'Position',[270 370 450 16], ...
    'FontSize',9,'FontWeight','bold','FontColor',TXT_ACC);
ax3 = uiaxes(fig,'Position',[268 12 508 354]);
ax3.Color      = [0.10 0.10 0.13];
ax3.XColor     = TXT_DIM;
ax3.YColor     = TXT_DIM;
ax3.Title.Color= TXT_WHT;
 
% Recommendations box
uilabel(fig,'Text','RECOMMENDATIONS', ...
    'Position',[786 370 400 16], ...
    'FontSize',9,'FontWeight','bold','FontColor',TXT_ORG);
recBox = uitextarea(fig, ...
    'Position',[784 12 548 354], ...
    'Editable','off', ...
    'BackgroundColor',[0.10 0.10 0.13], ...
    'FontColor',[0.85 0.90 0.85],'FontSize',11, ...
    'Value',{'Select a use case above','and click  RECOMMEND'});
 
% ════════════════════════════════════════════════════════════
%  NESTED FUNCTIONS
% ════════════════════════════════════════════════════════════
 
    function showInfo()
        selected = lst.Value;
        if isempty(selected)
            infoBox.Value = {'Click any material to view its applications.'};
            return
        end
        name = selected{end};
        idx  = find(strcmp(mat.Name, name));
        if ~isempty(idx)
            parts = strsplit(mat.Info{idx}, ':');
            if length(parts) >= 2
                infoBox.Value = {['[' parts{1} ']'], '', strtrim(parts{2})};
            else
                infoBox.Value = {mat.Info{idx}};
            end
        end
    end
 
    function updateDashboard()
        selected = lst.Value;
        if isempty(selected)
            status.Text = 'Please select at least one material.';
            return
        end
        idx = find(ismember(mat.Name, selected));
 
        % Table
        data = table(...
            mat.E(idx)', mat.Yield(idx)', mat.Tensile(idx)', ...
            mat.Density(idx)', mat.Hardness(idx)', ...
            mat.Poisson(idx)', mat.STW(idx)', ...
            'VariableNames',{'E(GPa)','Yield(MPa)','Tensile(MPa)', ...
                             'Density','Hardness','Poisson','STW'}, ...
            'RowNames', selected);
        tbl.Data = data;
 
        % Bar Chart
        propMap = containers.Map(...
            {'Young''s Modulus (GPa)','Yield Strength (MPa)', ...
             'Tensile Strength (MPa)','Density (g/cm3)', ...
             'Hardness (HB)','Strength-to-Weight Ratio'}, ...
            {mat.E,mat.Yield,mat.Tensile,mat.Density,mat.Hardness,mat.STW});
        vals = propMap(dd.Value);
        cla(ax1);
        b = bar(ax1, vals(idx));
        ax1.XTick = 1:length(idx);
        ax1.XTickLabel = selected;
        ax1.XTickLabelRotation = 22;
        ax1.Title.String = dd.Value;
        ax1.YLabel.String = dd.Value;
        ax1.YLabel.Color  = TXT_DIM;
        b.FaceColor = 'flat';
        b.CData     = lines(length(idx));
        b.EdgeColor = 'none';
 
        % STW Chart — colored bars
        cla(ax2);
        cols = lines(length(idx));
        hold(ax2,'on');
        for k = 1:length(idx)
            bh = barh(ax2, k, mat.STW(idx(k)));
            bh.FaceColor = cols(k,:);
            bh.EdgeColor = 'none';
        end
        hold(ax2,'off');
        ax2.YTick      = 1:length(idx);
        ax2.YTickLabel = selected;
        ax2.Title.String = 'Strength-to-Weight Ratio';
        ax2.XLabel.String = 'MPa / (g/cm3)';
        ax2.XLabel.Color  = TXT_DIM;
 
        % Radar
        drawRadar(idx, selected);
 
        status.Text = ['Comparing ' num2str(length(idx)) ' material(s).'];
    end
 
    function drawRadar(idx, names)
        cla(ax3);
        props = [mat.E; mat.Yield; mat.Tensile; ...
                 mat.Density; mat.Hardness; mat.STW];
        propLabels = {'E (GPa)','Yield','Tensile','Density','Hardness','STW'};
        nP     = size(props,1);
        normed = zeros(size(props));
        for p = 1:nP
            mn = min(props(p,:)); mx = max(props(p,:));
            if mx > mn
                normed(p,:) = (props(p,:)-mn)/(mx-mn);
            end
        end
        angles = linspace(0,2*pi,nP+1);
        angles(end) = angles(1);
        cols = lines(length(idx));
        hold(ax3,'on');
        for g = 0.25:0.25:1.0
            plot(ax3, g*cos(angles), g*sin(angles), ...
                'Color',[0.25 0.25 0.30],'LineWidth',0.8);
        end
        for p = 1:nP
            plot(ax3,[0 cos(angles(p))],[0 sin(angles(p))], ...
                'Color',[0.30 0.30 0.35],'LineWidth',0.8);
            text(ax3, 1.22*cos(angles(p)), 1.22*sin(angles(p)), ...
                propLabels{p},'Color',ACCENT, ...
                'HorizontalAlignment','center','FontSize',10,'FontWeight','bold');
        end
        for m = 1:length(idx)
            v = normed(:,idx(m))';
            v(end+1) = v(1); %#ok
            xr = v.*cos(angles);
            yr = v.*sin(angles);
            plot(ax3,xr,yr,'-o','Color',cols(m,:), ...
                'LineWidth',2.5,'MarkerSize',6, ...
                'MarkerFaceColor',cols(m,:), ...
                'DisplayName',names{m});
            patch(ax3,xr,yr,cols(m,:), ...
                'FaceAlpha',0.12,'EdgeColor','none');
        end
        lgd = legend(ax3, names, 'Location','southoutside', ...
            'TextColor',TXT_WHT,'Color',[0.12 0.12 0.15], ...
            'EdgeColor',[0.3 0.3 0.3],'FontSize',9);
        lgd.NumColumns = min(3,length(names));
        ax3.Title.String = 'Radar — Normalized Properties';
        ax3.Title.Color  = TXT_WHT;
        ax3.Title.FontSize = 11;
        axis(ax3,'equal');
        ax3.XAxis.Visible = 'off';
        ax3.YAxis.Visible = 'off';
        hold(ax3,'off');
    end
 
    function exportCSV()
        if isempty(tbl.Data)
            status.Text = 'Nothing to export — compare first.';
            return
        end
        [file,path] = uiputfile('*.csv','Save Comparison As');
        if isequal(file,0); return; end
        writetable(tbl.Data,fullfile(path,file),'WriteRowNames',true);
        status.Text = ['Exported: ' file];
    end
 
    function showRecommendation()
        ucIdx   = find(strcmp(useCases, ucDrop.Value));
        recs    = recommendations{ucIdx};
        reasons = strsplit(reasonsMap{ucIdx},'|');
        out = {['=== ' upper(ucDrop.Value) ' ==='], ''};
        medals = {'#1','#2','#3'};
        for r = 1:length(recs)
            out{end+1} = [medals{r} '  ' recs{r}];
            out{end+1} = ['    -> ' reasons{r}];
            out{end+1} = '';
        end
        recBox.Value = out;
    end
 
    function clearAll()
        lst.Value = {};
        cla(ax1); cla(ax2); cla(ax3);
        tbl.Data  = {};
        infoBox.Value = {'Click any material to view its applications.'};
        recBox.Value  = {'Select a use case above','and click  RECOMMEND'};
        status.Text   = 'Cleared — ready for new comparison.';
    end
 
end
 